### PR TITLE
Add a way to let the user choose the vocab to use.

### PR DESCRIPTION
**Pull request by Daniel-KM**
The main issue is for subject, when it's common to use more than one vocabularies. Currently, there can be only one vocabulary by property, so it's not enough. This is the feature.

Ideally, it would be possible to pre-select multiple datatypes directly in the resource templates, but it may requires some change in the core (probably changing the datatype field into an array). So for the future.

### CODE REVIEW

**Comment by Daniel-KM** [comment]
About the improvement on the resource templates above, the resource templates is a very good feature in Omeka, but the ux to custom a property is not good: the form is hidden in a far sub menu, in a small bottom corner, where the datatypes are hard to select. @kimisgold , if you have some ideas.

**Comment by jimsafley** [comment]
I'm not going to merge this, at least not until I have the time to contemplate the consequences of what seems to be a departure from original intent of the module. I'm not convinced that your approach to offer up _every_ vocabulary for _every_ ValueSuggest data type is the right one.

Even so, you raise a good point about the need some may have to select more than one vocabulary. One solution is to implement a data type/suggester that draws from multiple endpoints, I think that's the way to go for now.

We do need to address the less-than-optimal resource template interface, as you suggest, but I don't think we should allow users to select multiple data types for one property. Though, feel free to create an issue on that repository (if you haven't already).

**Comment by Daniel-KM** [comment]
Ok, I'm going to improve the process to get more than one vocabulary, but not all.  
My users want only two or three vocabularies for subjects (plus free keywords), so it's not a lot. Note that by default, the user has five datatypes to choose (literal, three resource types and uri).

**Comment by Daniel-KM** [comment]
Rebased and fixed the bug that display the select of the full list in all properties.

**Pull request closed without merging**
